 <footer>
     <p> Website by: </p>
     <p><br /> Carlos Williams - <a href = "mailto:104246730@student.swin.edu.au">104246730@student.swin.edu.au</a></p>
     <p> Bao An - <a href = "mailto:103485260@student.swin.edu.au">103485260@student.swin.edu.au</a></p>
     <p> Halim Vlahos - <a href = "mailto:104015943@student.swin.edu.au">104015943@student.swin.edu.au</a></p>
     <p> Ngo Thao Ngan - <a href = "mailto:104055130@student.swin.edu.au">104055130@student.swin.edu.au</a></p>
     <p> Ryan Chee - <a href = "mailto:104249483@student.swin.edu.au">104249483@student.swin.edu.au</a></p>
 </footer>
  

