<div class="navbar">
      <a href="index.php">HOME</a>      
      <div class="dropdown">
        <button class="dropbtn">PRODUCTS
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
          <a href="product.php">SEE ALL PRODUCTS</a>
          <a href="product.php#1">Beetle</a>
          <a href="product.php#2">Lowrider</a>
          <a href="product.php#3">Ranger</a>
        </div>
      </div>
      <a href="payment.php">PAYMENT</a>
      <a href="about.php">ABOUT</a>
      <a href="enhancements.php">ENHANCEMENTS</a>
    </div>
